### ISSUE TITLE
Documentation Link Broken

### ISSUE THREAD

**Issue by kopertop** [SumoLogic/sumologic-aws-lambda#11]
It would have been tremendously helpful to have this link included in the README, as the original link in the lambda script points to a place that didn't work for me:

http://help.sumologic.com/Apps/AWS_Lambda/Collect_Logs_for_AWS_Lambda?t=1461360129021

**Comment by duchatran** [comment]
Tks @kopertop ! I added the link to the README file under the CloudWatchLogs folder.
