### ISSUE TITLE
nodejs12 support?

### ISSUE THREAD

**Issue by mwarkentin** [SumoLogic/sumologic-aws-lambda#126]
Hello,

Are there plans to upgrade the nodejs runtime from 10 -> 12?

**Comment by jeffgus** [comment]
My Trusted Advisor dashboard is warning me that the Sumo lambda functions are using NodeJS10 which is scheduled to be deprecated. I deployed via Cloudformation.

**Comment by SumoSourabh** [comment]
Provided support for NodeJS 12 / NodeJS 14 versions. Please check release - https://github.com/SumoLogic/sumologic-aws-lambda/releases/tag/v1.2.9
