### ISSUE TITLE
Any plan for a new release? The last one (v1.2.8) was created in Oct 2019.

### ISSUE THREAD

**Issue by buptliuhs** [SumoLogic/sumologic-aws-lambda#137]
Hi,

Code on master already supports node14, however, the latest release (v1.2.8) is still node8 which is NOT supported by AWS Lambda.

To stay a valid open-source project, I believe the release tag needs to catch up.

Thanks!
Tony

**Comment by SumoSourabh** [comment]
Released a new version with details of all updates to AWS runtime versions - https://github.com/SumoLogic/sumologic-aws-lambda/releases/tag/v1.2.9

**Comment by SumoSourabh** [comment]
Let me know if we can close the issue.
