### ISSUE TITLE
Potential SAR Vulnerability

### ISSUE THREAD

**Issue by johspaeth** [SumoLogic/sumologic-aws-lambda#142]
Hi @SumoSourabh 

The [Readme.md](https://github.com/SumoLogic/sumologic-aws-lambda/blob/main/cloudwatchevents/README.md#running-tests) for the CloudWatchEvents deployments needs an update, as it contains an AWS SAR security vulnerability that has been recently discovered. We wrote a [detailed explanation](https://codeshield.io/blog/2021/08/26/sar_confused_deputy/) on the vulnerability.  

It is important to add a link to the source account that deploys to the bucket by adding an additional condition.
 
```
            Condition:
              StringEquals:
                "aws:SourceAccount":  <AWS::AccountId>
```

 @SumoSourabh  I am tagging you as I have seen that you recently modified the file.

**Comment by himsharma01** [comment]
Thanks @johspaeth for pointing this out. We have fixed this SAR vulnerability on our side. PR: https://github.com/SumoLogic/sumologic-aws-lambda/pull/174
