### ISSUE TITLE
Support arm64 runtime and Node16?

### ISSUE THREAD

**Issue by ashish-desai-massmutal** [SumoLogic/sumologic-aws-lambda#153]
Any plans to validate and support the code to run on ARM64 and Node16 runtime?  
ARM64 will help reduce customer operational costs.

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by volphy** [comment]
I am not sure what you mean by supporting ARM64 & Node 16 managed runtime.

I have tried running the older Lambda function:
https://github.com/SumoLogic/sumologic-aws-lambda/blob/main/cloudwatchlogs/cloudwatchlogs_lambda.js

on ARM 64 & Node 18 managed runtime.

It seems to work out-of-the-box.

**Comment by himsharma01** [comment]
Thanks for your reply @volphy .
@ashish-desai-massmutal we have released new versions of lambda code which supports Node 18.x . Can you please give them a try.
Thanks

**Comment by volphy** [comment]
I do not use Sumo Logic now so I cannot test it.
