### ISSUE TITLE
Dead link in cloudwatchlogs README.md

### ISSUE THREAD

**Issue by zellio** [SumoLogic/sumologic-aws-lambda#159]
The deprecation warning in cloudwarchlogs/README.md links to a page which does not exist

https://github.com/SumoLogic/sumologic-aws-lambda/blob/main/cloudwatchlogs/README.md?plain=1#L5-L6

Steps to reproduce:

https://help.sumologic.com/Send-Data/Collect-from-Other-Data-Sources/Amazon-CloudWatch-Logs

Proposed resolution:

Update link with correct documentation.

**Comment by himsharma01** [comment]
The link re-direction has been fixed. Closing the issue.
