### ISSUE TITLE
cloudwatchlogs_lambda should send a batch of messages to Sumo instead of sending them one by one

### ISSUE THREAD

**Issue by AlexKorostov** [SumoLogic/sumologic-aws-lambda#16]
CloudWatch supports passing several log messages to the streaming lambda.

In many cases CloudWatch passes several log messages in one event. Current implementation of cloudwatchlogs_lambda.js splits the messages and sends them to Sumo HTTP collector one by one. 

Why not send all the messages in a single HTTP request (similar to what Log4J Sumo adapter does)?

**Comment by stevezau** [comment]
This will be fixed when #19 is merged
