### ISSUE TITLE
Update deprecated Lambda runtime for SecurityHubCollectorFunction

### ISSUE THREAD

**Issue by charles-niaid** [SumoLogic/sumologic-aws-lambda#184]
The Python 3.7 Lambda runtime has been [deprecated](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy), but the `SecurityHubCollectorFunction` is still using it.

https://github.com/SumoLogic/sumologic-aws-lambda/blob/305e7cff54faa1a23f3342b8e83f444efa19291f/securityhub-collector/sam/template.yaml#L20

**Comment by himsharma01** [comment]
Hey @charles-niaid , Thanks for raising the git issue. We have updated the lambda runtime of the same. 
https://github.com/SumoLogic/sumologic-aws-lambda/blob/main/securityhub-collector/sam/template.yaml#L38
Do you mind checking the latest version please.
Thanks
