### ISSUE TITLE
errors is not defined, messageList never cleared

### ISSUE THREAD

**Issue by baversjo** [SumoLogic/sumologic-aws-lambda#22]
The variable `errors` in cloudwatchlogs_lambda.js line 121 is not defined.
When the http connection fails it would be nice to know the http response code.

**Comment by baversjo** [comment]
Also, the variable containing the list of logs to be sent, `messageList`, is never cleared. It should be cleared after a successful POST to sumologic. AWS Lambda will reuse the same container for performance purposes[1], causing messageList to fill with more and more submitted messages. This lead to the same logs being submitted many times to Sumologic, causing a data ingest limit on my account and also going over my daily quotas.
[1]: https://aws.amazon.com/blogs/compute/container-reuse-in-lambda/

**Comment by stevezau** [comment]
@baversjo hmm I didn't realise it was reused. That's absolutely an issue. I'll fix that shortly.

Thanks!
