### ISSUE TITLE
support for unicode characters for logging

### ISSUE THREAD

**Issue by miguelpico** [SumoLogic/sumologic-aws-lambda#28]
The data extracted from the stream to be sent to sumo is being done in 'ascii' vs 'utf-8' so the lambda fails when a log statement contains unicode (see offending code below)

var awslogsData = JSON.parse(buffer.toString('ascii'));

cc @jefftrudeau

**Comment by himanshu219** [comment]
default encoding is utf 8 in all functions. Closing this as deprecated.
