### ISSUE TITLE
Regex is not working

### ISSUE THREAD

**Issue by caevv** [SumoLogic/sumologic-aws-lambda#41]
This doesn't seem to be working:

```javascript
// Regex used to detect logs coming from lambda functions.
// The regex will parse out the requestID and strip the timestamp
// Example: 2016-11-10T23:11:54.523Z	108af3bb-a79b-11e6-8bd7-91c363cc05d9    some message
var consoleFormatRegex = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z\t(\w+?-\w+?-\w+?-\w+?-\w+)\t/;
```

A simple message like this: ```"START RequestId: be746bac-efd6-11e7-9740-0f2037ef62c0 Version: $LATEST\n";``` is returning null.

**Comment by duchatran** [comment]
Thanks, which function is this @caevv ?

**Comment by caevv** [comment]
https://github.com/SumoLogic/sumologic-aws-lambda/blob/master/cloudwatchlogs/cloudwatchlogs_lambda.js#L27

**Comment by himanshu219** [comment]
Resolved in this PR https://github.com/SumoLogic/sumologic-aws-lambda/pull/61
