### ISSUE TITLE
How to Set Up Sumo Logic App for Amazon VPC Flow Logs

### ISSUE THREAD

**Issue by sirmdub** [SumoLogic/sumologic-aws-lambda#5]
Hi, for lack of a better place to ask this, I came across this github while googling. How in the world do you set up the "Sumo Logic App for Amazon VPC Flow Logs" application, referenced in Sumologic docs here: https://service.sumologic.com/help/Default.htm#Amazon_VPC_Flow_Logs_App.htm%3FTocPath%3DApps%7CSumo%2520Logic%2520App%2520for%2520Amazon%2520VPC%2520Flow%2520Logs%7C_____0

Is that what this lambda streaming setup described in this github for? Any help or documentation would be much appreciated!

**Comment by duchatran** [comment]
@sirmdub: there are a couple of ways to setup data ingestion, Lambda being the easiest one. Once you setup data, you just need install the VPC app via the Sumo console as usual. (https://service.sumologic.com/help/Default.htm#Installing_Apps.htm%3FTocPath%3DApps%7CInstalling%2520Apps%2520from%2520the%2520Library%7C_____0)

Feel free to file a support ticket from the Sumo console for any further question. I'll close this issue for now, let me know if you have any other question.

**Comment by sirmdub** [comment]
Thanks. For future reference, the readme in this github instructions worked perfectly for setting up the Lambda to HTTP collector side of things. Its all working great!
