### ISSUE TITLE
loggroup-lambda-connector: connect existing log groups?

### ISSUE THREAD

**Issue by mwarkentin** [SumoLogic/sumologic-aws-lambda#50]
Hello!

I was wondering if there's a good way to subscribe existing log groups in addition to auto-subscribing new log groups that match the regex?

Maybe even just an example of how to invoke the lambda manually to subscribe if that's possible?

**Comment by himanshu219** [comment]
If you know the exact name then you can modify the function's handler and directly invoke
subscribeToLambda(logGroupName, env.LAMBDA_ARN, errorHandler)
if you know the regex and you have multiple log group function that will require fetching loggroup names using describeloggroups api (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatchLogs.html#describeLogGroups-property) and filtering the loggroups.

**Comment by mwarkentin** [comment]
@himanshu219 Thanks, I'll look into it!

**Comment by mwarkentin** [comment]
Added an idea to the portal: https://ideas.sumologic.com/ideas/SLP-I-3051

**Comment by sumo-apps-team** [comment]
@mwarkentin : just curious, do you have a lot of existing log groups? You can manually subscribe a log group from the console to an existing function as well

**Comment by mwarkentin** [comment]
Yes, we have a bunch of log groups. I ended up scripting a little shell script w/ the cli to subscribe our existing groups:

```
log_groups=$(aws logs describe-log-groups --log-group-name-prefix "${lg_prefix}" --profile ${profiles[${env}]} --query "logGroups[].logGroupName" --output text)
for lg in ${log_groups} ; do
  echo "Subscribing ${arns[${env}]} to ${lg}..."
  aws logs put-subscription-filter --log-group-name "${lg}" --filter-name "${env}-sumologic-cloudwatch" --filter-pattern "" --destination-arn "${arns[${env}]}" --profile ${profiles[${env}]}
done
```

**Comment by himanshu219** [comment]
The function now supports exist log groups.

**Comment by mwarkentin** [comment]
@himanshu219 Thanks, I assume that's this change here: https://github.com/SumoLogic/sumologic-aws-lambda/pull/57

Are there any details around how this works / how to use it?

**Comment by himanshu219** [comment]
Here is the documentation https://help.sumologic.com/Send-Data/Collect-from-Other-Data-Sources/Auto-Subscribe_AWS_Log_Groups_to_a_Lambda_Function. See **Step 5. Use the function to auto-subscribe existing log groups**
