### ISSUE TITLE
AWS Lambda: Node.js v4.x is now EOL

### ISSUE THREAD

**Issue by Elegroth** [SumoLogic/sumologic-aws-lambda#54]
AWS is removing support for Node.js v4.x.

New Lambda functions using Node.js v4.x will no longer be able to be created on July 31st, 2018.
Existing Lambda functions will no longer allow code updates on October 31st, 2018.

Requesting project to be updated to a newer Node.js version, preferably v8.

**Comment by duchatran** [comment]
Thanks @Elegroth. We are back-testing our functions, stay tuned.

**Comment by Vente1** [comment]
Any update on this?

**Comment by garimaahlawat21** [comment]
Any updates?

**Comment by himanshu219** [comment]
All the functions have been tested with node js 8.10 and their Cloud formation templates have been updated with the latest runtime.
