### ISSUE TITLE
No data displaying in SumoLogic

### ISSUE THREAD

**Issue by brycetho** [SumoLogic/sumologic-aws-lambda#6]
Running "cloudwatchlogs_lambda.js" as-is wasn't displaying any logs when searching sumologic. I added "toString" to the request, e.g.: 
`res.on('data', function(chunk) { body += chunk.toString(); });`
on line 32 and now see logs. I'm not super familiar with nodejs, but this seems to have worked for me.

**Comment by brycetho** [comment]
After some more looking, it seems like there is just an inconsistent delay and (maybe) an issue with timestamps. I think adding the "toString()" was a fluke and not needed.

**Comment by duchatran** [comment]
Bryce, could you check again? There could be some ingestion delay of of 1 or 2 minutes, but if the timestamp is not parsed correctly (or the timezone is off) then search won't return. Best way to check that data is received by Sumo is to search by Receipt time (check box User Receipt Time) near the Start button.

**Comment by duchatran** [comment]
@brycetho, I am close this for now, feel free to reopen if problem persists.

**Comment by brycetho** [comment]
I ran into both of those cases; that clears up my confusion. Thanks!
