### ISSUE TITLE
CloudFormation stack fails

### ISSUE THREAD

**Issue by schreierbrian** [SumoLogic/sumologic-aws-lambda#74]
The CF stack launched by this application fails to complete, rolling back with an error that the IAM role aws-serverless-repository-CloudWatchEventFunctionR-1IATRDMOBCJVM doesn't exist
![image](https://user-images.githubusercontent.com/43552476/47509195-96403980-d843-11e8-857b-0fc460bdbb07.png)

**Comment by himanshu219** [comment]
Are you able to replicate this issue I tried deploying the application in us-east-1 from serverless repo it installed perfectly fine.
<img width="1662" alt="screen shot 2018-10-30 at 3 56 56 pm" src="https://user-images.githubusercontent.com/3620468/47712311-5b803c00-dc5d-11e8-8c40-1ce8469d33c2.png">

**Comment by himanshu219** [comment]
closing this issue let us know if you are able to replicate this
