### ISSUE TITLE
Security Hub Collector and Forwarder are both missing from the Serverless Application Repository

### ISSUE THREAD

**Issue by wagneraw** [SumoLogic/sumologic-aws-lambda#86]
I'm attempting to setup the collector and forwarder for AWS Security Hub. The documentation(https://help.sumologic.com/07Sumo-Logic-Apps/01Amazon_and_AWS/AWS_Security_Hub/1-Ingest-findings-into-AWS-Security_Hub and https://help.sumologic.com/07Sumo-Logic-Apps/01Amazon_and_AWS/AWS_Security_Hub/2-Collect-findings-for-the-AWS-Security-Hub-App) sends you to the Serverless Application Repo for both of those apps, but neither of them show up when I search for sumo. I checked in multiple regions to make sure it wasn't a region thing, but got the same results.

![image](https://user-images.githubusercontent.com/20321937/53101737-5be85f80-34f8-11e9-8128-8c62c057bfad.png)

**Comment by himanshu219** [comment]
One needs to check the checkbox "show apps that create custom roles" see Step 2.3
