### ISSUE TITLE
Slow Log Processing with DLQ Lambda

### ISSUE THREAD

**Issue by wallabyies** [SumoLogic/sumologic-aws-lambda#92]
I'm seeing very slow processing of the CloudWatch dead letter queue by the SumoCWProcessDLQLambda.

The logs repeatedly show errors similar to this one:

`2019-05-03T16:05:44.119Z	bfc53687-23d5-4155-87f8-1804134eabfa	TypeError: Cannot read property 'data' of undefined
at /var/task/DLQProcessor.js:19:73
at Response.<anonymous> (/var/task/DLQProcessor.js:41:19)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:364:18)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)`

It appears there is some data in the queue that is causing the lambda to get hung up.   Previously, the queue could be emptied very quickly.

**Comment by himanshu219** [comment]
DLQProcessor expects messages to be in following format { "awslogs": {"data": "BASE64ENCODED_GZIP_COMPRESSED_DATA"} }.  Can you provide more details on what types of logs you are trying to ingest to Sumo? Also would be good if you could try putting a print statement in DLQProcessor.js below line number 17 console.log(messages).

**Comment by wallabyies** [comment]
Can you give an example of the print statement?

**Comment by himanshu219** [comment]
console.log(message) // this is the print statement 
add this line  in DLQProcessor.js below line number 17

**Comment by himanshu219** [comment]
I have create a PR and have put a check to filter out invalid messages https://github.com/SumoLogic/sumologic-aws-lambda/pull/93 I have few questions for you though it seems that the messages you are getting is from CloudWatch Events. We have tested this integration with VPC Flow logs, Lambda logs, EC2 logs etc and haven't found this format. 
1> How are these messages getting inserted in the first place? 
2> Are you exporting CloudWatch events to LogGroups? 
3> Are these messages relevant for you and you want to ingest them to Sumo intentionally?

**Comment by wallabyies** [comment]
Ideally, we'd want these events ingested into Sumo if possible, otherwise discard if it's causing problems.

It looks like a CloudWatch event is triggering a lambda which is logging to a log group?    Just a guess.

**Comment by himanshu219** [comment]
I am not sure about that because if those events are logged by lambda to a log group then the metadata about loggroups/logstream name should have been there. I'll have to investigate this case for confirmation. For now you can redeploy the CF template it should pick up the new code.

**Comment by wallabyies** [comment]
Very good, thanks!

**Comment by himanshu219** [comment]
Let us know if that worked so we can close this issue.

**Comment by wallabyies** [comment]
This fixed the issue and can be closed.   Thank you for your help!
