### ISSUE TITLE
The containing application will need be updated before it can be deployed

### ISSUE THREAD

**Issue by suhailc** [SumoLogic/sumologic-aws-lambda#99]
Hi,

I'm getting the following error when trying to deploy the AWS Lambda function for "sumologic-guardduty-benchmark — version 1.0.5"

`The following nested application arn:aws:serverlessrepo:us-east-1:956882708938:applications/sumologic-app-utils and semantic version 1.0.5 was recreated after the containing application arn:aws:serverlessrepo:us-east-1:956882708938:applications/sumologic-guardduty-benchmark was published. The containing application will need be updated before it can be deployed`

Please advise/fix.

Regards,
Suhail.

**Comment by himanshu219** [comment]
is it resolved? Can you try to delete the stack and redeploy it Remember that the nested stack should also be deleted. Also I want to know whether you are deploying this SAM application first time or you are updating it.

**Comment by himanshu219** [comment]
Fix in [PR](https://github.com/SumoLogic/sumologic-aws-lambda/pull/102)
